#!/bin/sh

# Ottieni la luminosità corrente
CURRENT=$(brightnessctl | grep -oP '\d+(?=%)')

# Mostra un menu con dmenu per scegliere un nuovo valore di luminosità
NEW=$(dmenu -p "Luminosità [$CURRENT%]:")

# Imposta la nuova luminosità se il valore è valido
if [[ $NEW =~ ^[0-9]+$ ]] && ((NEW >= 0 && NEW <= 100)); then
    brightnessctl set "${NEW}%"
    echo "Luminosità impostata: $NEW%"
else
    echo "Errore: Valore non valido: $NEW" | dmenu -p "Errore:" -l 1
fi
