#!/bin/bash

# Mostra il volume attuale
VOLUME=$(amixer get Master | grep -oP '\d+%' | head -1 | tr -d '%')
# Mostra una casella di testo in dmenu per inserire il livello del volume
NEW_VOLUME=$(dmenu -p "Imposta volume [$VOLUME%]:")

# Imposta il volume se il valore è valido
if [[ $NEW_VOLUME =~ ^[0-9]+$ ]] && ((NEW_VOLUME >= 0 && NEW_VOLUME <= 100)); then
    amixer set Master "${NEW_VOLUME}%"
    echo "Volume impostato: $NEW_VOLUME%"
else
    echo "Errore: Valore non valido" | dmenu -p "Errore:" -l 1
fi
